### ISSUE TITLE
rdc_sampler SIGSEGV with rocm 5.3.0

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#1062]
This is not necessarily the fault of the rdc_sampler plugin, but I wanted to record this for posterity while the information is fresh.`

The rdc_sampler is hitting a SIGSEGV in the amd code with rocm 5.3.0. It does not crash with 5.2.3.

rdc_sampler from ovis 4.3.9 (which appears to be the same as current head of ovis/OVIS-4)

Note that I did comment out two default rdc field IDs, RDC_FI_PCIE_TX and RDC_FI_PCIE_RX. Those do not work with the cards I was trying to use.

```
$ cat ~/src/sampler_rdc_sampler.conf
load name=rdc_sampler
config name=rdc_sampler producer=here instance=foo
start name=rdc_sampler interval=5000000
```

```
(gdb) run -F -x sock:8001 -c ./sampler_rdc_sampler.conf -v DEBUG
Starting program: /g/g0/morrone/local/ldms/sbin/ldmsd -F -x sock:8001 -c ./sampler_rdc_sampler.conf -v DEBUG
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x1555523ac700 (LWP 176646)]
[New Thread 0x1555521ab700 (LWP 176647)]
[New Thread 0x155551faa700 (LWP 176648)]
[New Thread 0x15555199e700 (LWP 176649)]
Fri Nov 11 15:02:41 2022: INFO      : Listening on sock:8001 using `sock` transport and `none` authentication
Fri Nov 11 15:02:41 2022: DEBUG     : Checking for rdc_sampler in /g/g0/morrone/local/ldms/lib/ovis-ldms
Fri Nov 11 15:02:41 2022: DEBUG     : rdc_sampler: get_plugin called
Fri Nov 11 15:02:41 2022: DEBUG     : msg_no 3 flags 3 rec_len 28 rsp_err 0
Fri Nov 11 15:02:41 2022: DEBUG     : rdc_sampler: rdcinfo_config_find_int_value warmup 4
Fri Nov 11 15:02:41 2022: DEBUG     : rdc_sampler: rdcinfo_config_find_int_value update_freq 1000000
Fri Nov 11 15:02:41 2022: DEBUG     : rdc_sampler: rdcinfo_config_find_int_value max_keep_age 60
Fri Nov 11 15:02:41 2022: DEBUG     : rdc_sampler: rdcinfo_config_find_int_value max_keep_samples 10
Missing separate debuginfo for /opt/rocm-5.3.0/lib/librocm_smi64.so.5
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/f0/018f53630e14880f37fa91acee2f321ff0fcf7.debug
[New Thread 0x1555504f3700 (LWP 176650)]
[New Thread 0x1555502f2700 (LWP 176651)]
[New Thread 0x155543fff700 (LWP 176652)]

Thread 1 "ldmsd" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-189.5.el8_6.x86_64 libcap-2.48-2.el8.x86_64 libgcc-8.5.0-10.1.el8_6.x86_64 libstdc++-8.5.0-10.1.el8_6.x86_64 openssl-libs-1.1.1k-7.el8_6.x86_64 zlib-1.2.11-19.el8_6.x86_64
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000155543b84db6 in ras_lib::RasRdcEnvironment::~RasRdcEnvironment() () from /opt/rocm-5.3.0/lib/../lib/rdc/librdc_ras.so
#2  0x0000155543b66ebb in void __gnu_cxx::new_allocator<ras_lib::RasRdcEnvironment>::destroy<ras_lib::RasRdcEnvironment>(ras_lib::RasRdcEnvironment*) () from /opt/rocm-5.3.0/lib/../lib/rdc/librdc_ras.so
#3  0x0000155543b66e0b in void std::allocator_traits<std::allocator<ras_lib::RasRdcEnvironment> >::destroy<ras_lib::RasRdcEnvironment>(std::allocator<ras_lib::RasRdcEnvironment>&, ras_lib::RasRdcEnvironment*) ()
   from /opt/rocm-5.3.0/lib/../lib/rdc/librdc_ras.so
#4  0x0000155543b66b3b in std::_Sp_counted_ptr_inplace<ras_lib::RasRdcEnvironment, std::allocator<ras_lib::RasRdcEnvironment>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() () from /opt/rocm-5.3.0/lib/../lib/rdc/librdc_ras.so
#5  0x0000155543b6039c in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() () from /opt/rocm-5.3.0/lib/../lib/rdc/librdc_ras.so
#6  0x0000155543b5fbd7 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() () from /opt/rocm-5.3.0/lib/../lib/rdc/librdc_ras.so
#7  0x0000155543b630e4 in std::__shared_ptr<ras_lib::RasEnvironment, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() () from /opt/rocm-5.3.0/lib/../lib/rdc/librdc_ras.so
#8  0x0000155543b63126 in std::shared_ptr<ras_lib::RasEnvironment>::~shared_ptr() () from /opt/rocm-5.3.0/lib/../lib/rdc/librdc_ras.so
#9  0x0000155543b62e25 in ras_lib::RasEnvironment::GetEnvironment(ras_mode_t) () from /opt/rocm-5.3.0/lib/../lib/rdc/librdc_ras.so
#10 0x0000155543baf22b in ras_lib::rdc::RasModule::Init(unsigned long) () from /opt/rocm-5.3.0/lib/../lib/rdc/librdc_ras.so
#11 0x0000155543bbcb80 in rdc_module_init () from /opt/rocm-5.3.0/lib/../lib/rdc/librdc_ras.so
#12 0x00001555509b9e98 in amd::rdc::RdcRasLib::RdcRasLib(char const*) () from /opt/rocm-5.3.0/lib/librdc.so
#13 0x00001555509c702c in amd::rdc::RdcModuleMgrImpl::get_telemetry_module() () from /opt/rocm-5.3.0/lib/librdc.so
#14 0x00001555509b7b72 in amd::rdc::RdcWatchTableImpl::rdc_field_watch(unsigned int, unsigned int, unsigned long, double, unsigned int) () from /opt/rocm-5.3.0/lib/librdc.so
#15 0x000015555549633a in rdcinfo_hardware_init (inst=0x6c1510) at rdcinfo.c:451
#16 rdcinfo_config (inst=inst@entry=0x6c1510, avl=avl@entry=0x6a84e0) at rdcinfo.c:630
#17 0x0000155555495658 in config (self=<optimized out>, kwl=<optimized out>, avl=0x6a84e0) at rdc_plugin.c:88
#18 0x000000000040ecd9 in ldmsd_config_plugin (plugin_name=plugin_name@entry=0x6bbe50 "rdc_sampler", _av_list=_av_list@entry=0x6a84e0, _kw_list=_kw_list@entry=0x6bb220) at ldmsd_config.c:315
#19 0x000000000041570a in plugn_config_handler (reqc=0x6bc670) at ldmsd_request.c:4848
#20 0x0000000000418f4e in ldmsd_handle_request (reqc=reqc@entry=0x6bc670) at ldmsd_request.c:904
#21 0x0000000000419334 in ldmsd_process_config_request (xprt=xprt@entry=0x7fffffff8a30, request=request@entry=0x69cd10) at ldmsd_request.c:1221
#22 0x000000000040f713 in __process_config_file (path=path@entry=0x6478b0 "./sampler_rdc_sampler.conf", lno=lno@entry=0x7fffffff8ab8, trust=trust@entry=1, ctxt=<optimized out>, req_filter=0x40f2a0 <__req_filter_failover>) at ldmsd_config.c:701
#23 0x000000000040fbd5 in process_config_file (path=path@entry=0x6478b0 "./sampler_rdc_sampler.conf", lno=lno@entry=0x7fffffff8ab8, trust=trust@entry=1) at ldmsd_config.c:914
#24 0x000000000040a83a in main (argc=8, argv=0x7fffffff8d88) at ldmsd.c:2364

```

**Comment by baallan** [comment]
@miketxli do you or someone else at amd have time to look into with this?

**Comment by morrone** [comment]
I opened a rocm version of this issue here: RadeonOpenCompute/rdc/issues/4

**Comment by morrone** [comment]
AMD believes this to be a librdc bug, and intends to fix in the next rocm release.
