### ISSUE TITLE
ldmsd_controller : 'ldmsdInbandConfig' object has no attribute 'ldms'

### ISSUE THREAD

**Issue by puneet336** [ovis-hpc/ovis#1077]
Hi ,
I am trying to explore LDMS on rocky linux 8.6, and i am facing following issue while running ldmsd_controller command. 

issue#1  - post installation , i noted that  ldmsd_controller was not present in /opt/ovis
```
[root@ansi01 ovis-4.3.8]# which ldmsd_controller
/usr/bin/which: no ldmsd_controller in (/opt/ovis/sbin:/opt/ovis/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

```
issue #2 - the ldmsd_controller script was still present in source directory so i tried running it as - 
```
[root@ansi01 ovis-4.3.8]# find . -name ldmsd_controller
./ldms/python/ldmsd/ldmsd_controller
[root@ansi01 ovis-4.3.8]# ./ldms/python/ldmsd/ldmsd_controller  --host localhost --xprt sock --port 10008
Traceback (most recent call last):
  File "./ldms/python/ldmsd/ldmsd_controller", line 64, in <module>
    from ldmsd import ldmsd_config, ldmsd_util, ldmsd_request
ModuleNotFoundError: No module named 'ldmsd'
```

issue #3   - Here's how i adjusted PYTHONPATH and tried again - 
```
[root@ansi01 ovis-4.3.8]# export PYTHONPATH=$PYTHONPATH:/root/LDMS/ovis-4.3.8/ldms/python/
[root@ansi01 ovis-4.3.8]# ./ldms/python/ldmsd/ldmsd_controller  --host localhost --xprt sock --port 10008
Failed to import ovis_ldms.ldms.
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/root/LDMS/ovis-4.3.8/ldms/python/ldmsd/ldmsd_config.py", line 280, in __del__
    if self.ldms:
AttributeError: 'ldmsdInbandConfig' object has no attribute 'ldms'
```

```
[root@ansi01 ovis-4.3.8]# ./ldms/python/ldmsd/ldmsd_controller  --host localhost --xprt sock --port 10008
Failed to import ovis_ldms.ldms.
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/root/LDMS/ovis-4.3.8/ldms/python/ldmsd/ldmsd_config.py", line 280, in __del__
    if self.ldms:
AttributeError: 'ldmsdInbandConfig' object has no attribute 'ldms'
[root@ansi01 ovis-4.3.8]#
```

and i am currently stuck at this issue.
Did i miss anything during the install procedure ? 
Please advice.

Here is some more background into how i have downloaded and installed ldms.
1. installation
```
wget https://github.com/ovis-hpc/ovis/archive/refs/tags/v4.3.8.tar.gz
tar -xf v4.3.8.tar.gz
cd ovis-4.3.8
sh autogen.sh
 ./configure --prefix=/opt/ovis/
make 
make install
```

stdout logs are  [here](https://github.com/ovis-hpc/ovis/files/10292615/stdout.txt).

The environment variables - 
```
[root@ansi01 ovis-4.3.8]# cat /opt/ovis/env.src
#!/bin/bash
TOP=/opt/ovis
export LD_LIBRARY_PATH=$TOP/lib/:$LD_LIBRARY_PATH
export LDMSD_PLUGIN_LIBPATH=$TOP/lib/ovis-ldms
export ZAP_LIBPATH=$TOP/lib/ovis-ldms
export PYTHONPATH=$TOP/lib/python3.6/site-packages/:$PYTHONPATH
export PATH=$TOP/sbin:$TOP/bin:$PATH
```
content of bin,sbin and lib directory is [attached](https://github.com/ovis-hpc/ovis/files/10292653/contents.txt)
 

here's how started and tested LDMSD - 
```
[root@ansi01 ovis-4.3.8]# source /opt/ovis/env.src
[root@ansi01 ovis-4.3.8]# netstat -tulpn|grep -i 10008
[root@ansi01 ovis-4.3.8]# ldmsd -x sock:10008 -l $PWD/ldms1.log
[root@ansi01 ovis-4.3.8]# netstat -tulpn|grep -i 10008
tcp        0      0 0.0.0.0:10008           0.0.0.0:*               LISTEN      185693/ldmsd
[root@ansi01 ovis-4.3.8]# which ldmsd
/opt/ovis/sbin/ldmsd
[root@ansi01 ovis-4.3.8]# ldms_ls -h localhost -x sock -p 10008
[root@ansi01 ovis-4.3.8]# echo $?
0
[root@ansi01 ovis-4.3.8]# which ldms_ls
/opt/ovis/sbin/ldms_ls
[root@ansi01 ovis-4.3.8]# which ldmsd_controller
/usr/bin/which: no ldmsd_controller in (/opt/ovis/sbin:/opt/ovis/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
```

**Comment by puneet336** [comment]
resolved after using separate directory for configure and installing cython
